// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const allUserFeedFollows = `-- name: AllUserFeedFollows :many
SELECT id, user_id, feed_id, created_at, updated_at FROM users_feeds
WHERE user_id = $1
`

func (q *Queries) AllUserFeedFollows(ctx context.Context, userID uuid.UUID) ([]UsersFeed, error) {
	rows, err := q.db.QueryContext(ctx, allUserFeedFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersFeed
	for rows.Next() {
		var i UsersFeed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFeedFollow = `-- name: CreateFeedFollow :one
INSERT INTO users_feeds(id, user_id, feed_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, feed_id, created_at, updated_at
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (UsersFeed, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UsersFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedFollow = `-- name: DeleteFeedFollow :exec
DELETE FROM users_feeds
WHERE id = $1
AND user_id = $2
`

type DeleteFeedFollowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollow, arg.ID, arg.UserID)
	return err
}

const userFeedFollows = `-- name: UserFeedFollows :many
SELECT id, user_id, feed_id, created_at, updated_at FROM users_feeds
WHERE user_id = $1
`

func (q *Queries) UserFeedFollows(ctx context.Context, userID uuid.UUID) ([]UsersFeed, error) {
	rows, err := q.db.QueryContext(ctx, userFeedFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersFeed
	for rows.Next() {
		var i UsersFeed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
